### ISSUE TITLE
Whats wrong?

### ISSUE THREAD

**Issue by DeAlexPesh** [immense/Remotely#565]
![image](https://user-images.githubusercontent.com/16735261/212935542-8999a40a-2a3f-4378-bd3e-45af6bbac6e1.png)

client apps and bash scripts with link http://...

make please client colors as HEX without scroll
and add possibility for change connect scheme for client apps (https or http)

<details>
  <summary>remotely.yml</summary>

```
version: "3"
services:
 remotely:
  image: immybot/remotely:latest
  container_name: "remotely"
  ports:
   - "0.0.0.0:5000:5000"
  volumes:
   - "/app/remotely/remotely-data:/remotely-data"
  networks:
   - remotely
  logging:
   driver: "json-file"
   options:
    max-size: "200k"
    max-file: "5"
  restart: always

networks:
 remotely:
  driver: bridge
  name: remotely
```

</details>

<details>
  <summary>appsettings.json</summary>

```
{
  "ConnectionStrings": {
    "PostgreSQL": "Host=localhost;Database=Remotely;Username=postgres;",
    "SQLite": "DataSource=/remotely-data/Remotely.db",
    "SQLServer": "Server=(localdb)\\mssqllocaldb;Database=Remotely-Server-53bc9b9d-9d6a-45d4-8429-2a2761773502;Trusted_Connection=True;MultipleActiveResultSets=true"
  },
  "Logging": {
    "LogLevel": {
      "Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware": "Information",
      "Default": "Information"
    }
  },
  "ApplicationOptions": {
    "AllowApiLogin": false,
    "BannedDevices": [],
    "DataRetentionInDays": 90,
    "DBProvider": "SQLite",
    "EnableWindowsEventLog": false,
    "EnforceAttendedAccess": false,
    "KnownProxies": [
      "188.17.148.78"
    ],
    "MaxConcurrentUpdates": 10,
    "MaxOrganizationCount": 1,
    "MessageOfTheDay": "",
    "RedirectToHttps": true,
    "RemoteControlNotifyUser": true,
    "RemoteControlRequiresAuthentication": false,
    "RemoteControlSessionLimit": 5,
    "Require2FA": false,
    "SmtpDisplayName": "Help",
    "SmtpEmail": "me.msg@...",
    "SmtpHost": "smtp....",
    "SmtpLocalDomain": "...",
    "SmtpCheckCertificateRevocation": true,
    "SmtpPassword": "...",
    "SmtpPort": 465,
    "SmtpUserName": "me.msg@...",
    "Theme": "Dark",
    "TrustedCorsOrigins": [],
    "UseHsts": true,
    "UseHttpLogging": true
  }
}
```

</details>

<details>
  <summary>nginx.conf</summary>

```
upstream http_help {
  server 192.168.1.8:5000;
}
server {
  listen 443 ssl http2;
  charset utf-8;

  server_name help.*;

  access_log /var/log/nginx/help.access.log main;
  error_log /var/log/nginx/help.error.log warn;

  access_log off;

  pagespeed off;

  include /etc/nginx/certs/ssl.conf;

  ssl_certificate /etc/nginx/certs/ssl/live/*/fullchain.pem;
  ssl_trusted_certificate /etc/nginx/certs/ssl/live/*/chain.pem;
  ssl_certificate_key /etc/nginx/certs/ssl/live/*/privkey.pem;
  
  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection keep-alive;
    proxy_cache_bypass $http_upgrade;
    proxy_http_version 1.1;
    
    # sub_filter '</head>' '<link rel="stylesheet" href="$scheme://$host/remotly/custom.css"></head>';
    # sub_filter_once on;

    proxy_pass http://http_help;
  }
  location ~ ^/(_blazor|AgentHub|ViewerHub|CasterHub) {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_cache_bypass $http_upgrade;
    proxy_http_version 1.1;

    proxy_pass http://http_help;
  }
  error_page 401 404 500 502 503 504 /fail.html;
  location = /fail.html {
    root /usr/share/nginx/html/files_app/fails;
    internal;
  }
}
```

</details>
