### ISSUE TITLE
Docker healthcheck

### ISSUE THREAD

**Issue by modem7** [immense/Remotely#592]
On Docker, a healthcheck for the image would be useful to make sure that the application can be self-healing in the event of failure. 

Even something like a curl request to a health endpoint would suffice.

**Comment by DeAlexPesh** [comment]
Hi, build image with curl or wget and docker-compose ex:
```
 healthcheck:
   test: curl -f -s http://localhost:5000/ || exit 1
   start_period: 20s
   interval: 1m30s
   timeout: 10s
   retries: 3
```
