### ISSUE TITLE
Remotely not running in Docker

### ISSUE THREAD

**Issue by lbouriez** [immense/Remotely#638]
Hello, I am trying to run remotely using Docker on Ubuntu.
My Docker-compose file looks like that:
```yaml
version: '3'

services:
  remotely:
    container_name: remotely
    image: immybot/remotely:latest
    ports:
      - 5000:5000
    volumes:
      - remotelydata:/remotely-data
    restart: unless-stopped

volumes:
  remotelydata:
```

The container doesnt start and get stucks on:
```log
Entered main script.
Starting Remotely server.
Failed to create CoreCLR, HRESULT: 0x80070008
Entered main script.
Starting Remotely server.
Failed to create CoreCLR, HRESULT: 0x80070008
Entered main script.
Starting Remotely server.
Failed to create CoreCLR, HRESULT: 0x80070008
...
```

**Comment by lbouriez** [comment]
Answering to myself, as explained [here](https://docs.linuxserver.io/faq#jammy), my host docker-engine is probably too old...
I used the short-term solution and updated my docker-compose has follow:
```yaml
version: '3'

services:
  remotely:
    container_name: remotely
    image: immybot/remotely:1369
    ports:
      - 5000:5000
    volumes:
      - remotelydata:/remotely-data
    restart: unless-stopped
    security_opt:
      - seccomp=unconfined

volumes:
  remotelydata:
```
