### ISSUE TITLE
Can't set http debug level - appsettings.json is unaccessible win docker

### ISSUE THREAD

**Issue by lordrak007** [immense/Remotely#775]
Hello,
since remotely is accessible only as docker image i have no clue how to access appsettings.json to setup logging level.
Unfortunatelly it cannot be set in web interface.
Problem is wrong ip address of client which is some internal docker IP. I am using nginx proxy and i setup X headers which are required.
Is possible add this setting to server GUI?
Thank you
Lordrak

**Comment by matthew-on-git** [comment]
appsettings.json gets created if it doesn't exist if you follow the instructions in readme on a linux host at /var/www/remotely/appsettings.json

I used docker compose, so I can keep a compose file in git. You can see the volume getting mapped at the last line.
```yaml
version: "3.8"
services:
  remotely:
    image: immybot/remotely:latest
    ports:
      - 5000:5000
    volumes:
      - /var/www/remotely:/remotely-data
```
