### ISSUE TITLE
Missing the Mac file: Remotely-MacOS-x64.zip on latest container

### ISSUE THREAD

**Issue by matthew-on-git** [immense/Remotely#808]
**Describe the bug**
The file is missing or the link is broken https://<remote.example.com>/Content/Remotely-MacOS-x64.zip (HTTP ERROR 404).

**To Reproduce**
1. Go to 'https://<remote.example.com>/downloads'
2. Click on the link for the zip file under the mac section 'macOS x64 Files Only'
3. This is also a problem with the install script, which does exist and runs up until it tries to download the zip from the same link.

**Remotely Version**
Server (can be found on about page): Version: 2023.09.11.1010
Agent (can be found in device card): N/A

**Expected Behavior**
Expected for the file to be at the link location.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: mac OS 12.7.2
 - Browser: Brave and Chrome

**Additional Context**
I'm using the latest docker container from here: https://hub.docker.com/r/immybot/remotely
Here is my docker-compose.yml
```yml
version: "3.8"
services:
  remotely:
    image: immybot/remotely:latest
    ports:
      - 5000:5000
    volumes:
      - /var/www/remotely:/remotely-data
```

- [X] I am running Remotely in Docker and not on my QNAP, Synology, or Internet Connected Toaster
