### ISSUE TITLE
Works, but keeps restarting

### ISSUE THREAD

**Issue by Somnius** [immense/Remotely#963]
Remotely docker running on a synology with portainer stack

```
version: "3.9"
services:
  remotely:
    container_name: Remotely
    image: immybot/remotely:latest
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:false
    restart: on-failure:5
    ports:
      - 5371:8080
    volumes:
      - /volume1/docker/remotely:/app/AppData:rw
    environment:
      - Remotely_ApplicationOptions__DbProvider=SQLite
      - ASPNETCORE_ENVIRONMENT=Production
```

It was working flawlessly for the first couple of months, but now it is restarting by itself every 5 to 10 minutes.

A couple of key points from the log stand out:

Data Protection Warning: The log shows a warning about storing keys in `/root/.aspnet/DataProtection-Keys`, which might not persist across container restarts. This could/may be causing issues, as important configuration or session information may not be saved, leading to unexpected behavior or restarts.

How could this be happening on an installation that was previously working without issues and where no configuration has been tampered with? No new users, nothing— even the PowerShell scripts that were inserted are the same. 🤷‍♂️

Help ?
